#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <database_name>"
    exit 1
fi

db_name="$1"

mongo "$db_name" --quiet <<EOF
var cursor = db.school.find({ "name": /^Holberton/ });
cursor.forEach(printjson);
EOF